### ISSUE TITLE
what does it do?

### ISSUE THREAD

**Issue by adamf663** [philippe44/LMS-reliable#2]
Could you put in a little bit of documentation?  I saw this plugin while perusing available plugins using logitechmediaserver and all it says is "reliable HTTP connection for lms".  Clicking 'more info' took me here, but I couldn't find any information.  If your plugin makes the HTTP connection reliable, in what way was it unreliable without the plugin?  What does it do?
thanks.

**Comment by philippe44** [comment]
When you'll move to 8.2, it will not be needed anymore as I've included its features (and more) inside LMS directly.

The idea was/is that some servers do not like very long HTTP sessions that happens when you stream on line content. A typical example are podcasts where most servers expect the client to download the episode as quickly as possible, close the connection and play it at leisure. If you stream real time, it means very often a one-hour connection to the server and that's not good, so they close it after ~15 mins. It also happen when you pause a track as under some circumstances, LMS might keep the connection open (most often it does not). It can also happen that the connection is simply dropped due to network failure in which case the track fails to play.

Reliable was solving that by making the connection sticky, i.e. re-opening when it was failing before all expected bytes have been received. In LMS 8.2, that is now included ("persistent" mode) with an additional mode ('cache", my preferred option) where online streams are cached as quickly as possible and served locally instead of having a sticky connection. Of course that does not work for live radio, so it falls back to the "persistent" mode automatically

**Comment by adamf663** [comment]
Thanks for the explanation. I also have squeezebox in my car and the long http session issue may explain why the system sometimes craps out at 5-10 minutes. The car is running dietpi on a raspberry pi, but only sees updates every 4-6 months. The backup made from the last time I took it out of the car has version 8.1.1. At home, my server seems to have version 8.1.1. 
I'll try either version 8.2 or your plugin and see if it fixes the car stereo's issue. 
99% of my listening is of music from a .flac file library. Certainly not like streamed radio; would I use cached mode? 
Thanks again for the speedy response.

**Comment by philippe44** [comment]
The cache mode will not help then. it only does when the file is provided *to* LMS through HTTP(S) - In other words, it works on the LMS-to-Audio-Source link, not the client-to-LMS link. In your case, I assume you have some VPN to your home LMS and if your DietPi client has an issue and drops the connection it will not help. Now, such connection loss is handle and LMS forces the player to retry when it reconnects, normally. I'd have to check if something is different in direct vs proxy though (I suggest you don't use direct in your case)

**Comment by adamf663** [comment]
At home, logitechmediaserver primarily uses a linux file system. 
In the car, I have a mirror of the music library on a 512GB microsdhc card. 
The issue in the car is sporadic and songs will typically stop after 2-5 minutes. My other theory is that the UPS misbehaves when the car has sat unused for over a week. I'll know during my next upgrade where I'm dumping the UPS for a homebrew power/shutdown controller that'll run on an adafruit trinket.;
